name: objd
version: 0.3.0

author: Stevertus <stevertusyt@gmail.com>
homepage: https://stevertus.com/objD
repository: https://github.com/Stevertus/objD
issue_tracker: https://github.com/Stevertus/objD/issues
documentation: https://stevertus.com/objD/documentation
description: objd is an Object Oriented framework for Building Minecraft Datapacks with ease
environment:
    sdk: ">=2.3.0 <3.0.0"
dependencies:
  meta: ^1.1.7
  colorize: ^2.0.0
  path: ^1.6.2
  watcher: ^0.9.7+10