name: objd
version: 0.4.5

homepage: https://objd.stevertus.com
repository: https://github.com/Stevertus/objD
issue_tracker: https://github.com/Stevertus/objD/issues
documentation: https://objd.stevertus.com/guide
description: objd is an Object Oriented framework for Building Minecraft Datapacks with ease
environment:
  sdk: ">=2.15.0 <3.0.0"
dependencies:
  ansicolor: ^2.0.1
  archive: ^3.3.0
  gson: ^0.1.6-dev
dev_dependencies:
  lints: ^2.0.1
  test: 